--CREATE TABLE TB_WORKER(
--        ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--        NAME VARCHAR(150),
--        DAILY_INCOME NUMERIC(20,2)
--); 
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES ('Bob', 200.0); 
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES ('Maria', 300.0); 
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES ('Alex', 250.0);